### ISSUE TITLE
Is the Kentico.Xperience.ImageProcessing package dependency needed?

### ISSUE THREAD

**Issue by liamgold** [Kentico/xperience-by-kentico-miniprofiler#13]
There is a package dependency on `Kentico.Xperience.ImageProcessing` package, is this actually needed by MiniProfiler? See: https://github.com/Kentico/xperience-by-kentico-miniprofiler/blob/0baee95626f022d9e6a162890ffd0b8d8edfb575/Directory.Packages.props#L13

I can't see a reason for it to be included as a dependency, but I might be mistaken?

It would be good to remove this as a dependency if it isn't needed.

**Comment by liparova** [comment]
Thanks for sharing your problem.  We'll take a look at it soon and consider adding it to the original integration.

**Comment by liamgold** [comment]
I have already done a PR which removes the redundant dependency, it would be great to get that merged

https://github.com/Kentico/xperience-by-kentico-miniprofiler/pull/14
 
It isn't great that Image Processing is being added to projects through this package, so I'd appreciate if we can merge in
