### ISSUE TITLE
Bug: Current version is dependent on Xperience v28.3.1 and fails in v29+

### ISSUE THREAD

**Issue by seangwright** [Kentico/xperience-by-kentico-miniprofiler#16]
**Describe the bug**

Because of the internal API moved in v29.0.0, [libraries dependent on Xperience v28 will not work in v29+ projects](https://github.com/Kentico/xperience-by-kentico-lucene/issues/50).

The current version of this library depends on v28.3.1 of Xperience.

This _can_ be resolved by ensuring there is an explicit dependency on v29+ of `Kentico.Xperience.WebApp`, but in Console apps the [Kentico.Xperience.Core](https://docs.kentico.com/developers-and-admins/api/use-the-xperience-by-kentico-api-externally#add-the-xperience-api-nuget-packages) package might be the only one included.

**To Reproduce**
1. Create a .NET console app
2. [Follow the instructions for using Xperience in an external project](https://docs.kentico.com/developers-and-admins/api/use-the-xperience-by-kentico-api-externally#add-the-xperience-api-nuget-packages)
3. Add the Miniprofiler library
4. Run the app
5. See exception

**Expected behavior**

A version of this library supporting v29 is available.

**Screenshots**

**Library Version**
v1.1.0

**Desktop (please complete the following information):**
 - OS: macOS (arm)

**Comment by liparova** [comment]
Hi Sean,  thanks for reporting this! We'll take a look at it as soon as we can and get back to you with an update.

**Comment by Sapphirress** [comment]
Hello Sean, we have just updated MiniProfiler to version 29.5.3. Thanks for reporting it and let us know if you find any issues :)
